### ISSUE TITLE
Failed to create layerview for layer title: 'Esri Admin Building' 

### ISSUE THREAD

**Issue by njakuschona** [conterra/mapapps-layer-buildingscene#1]
After starting the sample app on mapapps.version 4.14.0 (jsregistry 1.5.6; jsrt-test 2.0.2) following error appears in the console and no layer is displayed on the map:
 ![image](https://user-images.githubusercontent.com/46575458/205030583-88239caf-9af7-4597-872a-c21bafc49f0c.png)

**Comment by sholtkamp** [comment]
Cannot reproduce in map.apps 4.17.0
